name: CI/CD Data Quality

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      # - name: Rodar testes
      #   env:
      #     PYTHONPATH: ${{ github.workspace }}
      #   run: |
      #     pytest tests/

      - name: Lint
        run: |
          flake8 src tests

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy scripts e configs para S3
        run: |
          aws s3 sync src/ s3://ifood-case-data-quality/scripts/src/ --delete
          aws s3 sync config/ s3://ifood-case-data-quality/scripts/config/ --delete
          aws s3 sync libs/ s3://ifood-case-data-quality/scripts/libs/ --delete